spring.application.name=social

# تنظیمات اتصال به دیتابیس پستگرس
spring.datasource.url=jdbc:postgresql://localhost:5432/social_db
spring.datasource.username=postgres
spring.datasource.password=Arman@1365

# تنظیمات هایبرنیت (برای ساخت خودکار جداول)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# CHANGE_THIS_TO_A_RANDOM_BASE64_256BIT_SECRET
jwt.secret=o89CiGTKvmENQnUxVaixE5a+zxburIZjQLxVtwte+Fk=
jwt.expiration-ms=86400000

# ===== Kavenegar (برای شماره‌های +98) =====
kavenegar.api-key=
# اختیاری؛ اگر شماره اختصاصی/سرشماره دارید اینجا بگذارید، وگرنه خالی بگذارید
kavenegar.sender=

# ===== Twilio (برای بقیه دنیا) =====
twilio.account-sid=
twilio.auth-token=
# شماره‌ای که از پنل Twilio خریداری/تخصیص دادید (فرمت E.164، مثلا +1XXXXXXXXXX)
twilio.from-number=

# ===== Gmail SMTP (برای ایمیل) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amir.hendianpour@gmail.com
# این رمز عادی جیمیل نیست! باید "App Password" بسازید (توضیح پایین پیام)
spring.mail.password=vmjoclbzlwloscwy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
